x=(["cow","dog","dog","sheep","cat","rabbit","cow"])
print(x)
p="sheep"
print(list(p))
print(list(x))
t={"a","s","s","a","c"}
print(t)
print(len(t))
b={"n","k","p","l","Y"}
print(t|b)
f={1,2,3,4,5,6}
print(t.union(b,f))
print(t|b|f)
print(t.intersection(b,f))
y={1,2,3,4,5,6,50,60,70}
z={10,20,30,40,50,}
m={100,200,300,400}
print(y.intersection(z,m))
print(y.union(z,m))
print(y.difference(z,m))
print(y.difference(m))
print(z.difference(m))
print(y.isdisjoint(m))
print(f.issubset(y))
print(f.issuperset(y))
