from datetime import datetime
dt=datetime.strptime("2020-03-24","%Y-%m-%d")
print(dt)
from datetime import datetime,timedelta,timezone
JST=timezone(timedelta(hours=+9))
dt=datetime(2015,1,1,12,0,0,tzinfo=JST)
print(dt)
print(dt.tzname())
print("-"*56)
from datetime import date,time,datetime
d=date(year=2020,month=2,day=17)
print(d)
t=time(hour=13,minute=15,second=56)
print(t)
print("year:",d.year)
print("month:",d.month)
print("day:",d.day)
print(datetime(d.year,d.month,d.day,t.hour,t.minute,t.second))
print("_"*56)
from datetime import date,time,datetime
today=date.today()
print(today)
now=datetime.now()
print(now)
current_time=time(now.hour,now.minute,now.second)
print(current_time)
print("_"*56)
print("_"*78)
from datetime import datetime, timedelta
now=datetime.now()
print(now)
tomorrow=timedelta(days=+1)
print(tomorrow)
print(now+tomorrow)
yesterday=timedelta(days=-1)
print(yesterday)
print(now+yesterday)
delta=timedelta(days=+3, hours=-4, seconds=+10)
print(now+delta)
from dateutil.relativedelta import  relativedelta
tomorrow=relativedelta(days=+1, hours=-5)
print(now+tomorrow)
